spring:
  application:
    name: DouyuDanCrawler

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/danmu
    username: root
    password: root

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        # use camel case in database
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      database-platform: org.hibernate.dialect.
#    database: MYSQL

    # import sql
    properties.hibernate:
      connection.charSet: UTF-8
      dialect: org.hibernate.dialect.MySQL5Dialect
      hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.globally_quoted_identifiers: true

